<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://relaxng.org/ns/structure/1.0"?>
<package format="3">
  <name>drone_bridge</name>
  <version>0.1.0</version>
  <description>DJI -> ROS bridge: H.264 TCP decode and telemetry adapters.</description>
  <maintainer email="cristhian@example.com">cristhian</maintainer>
  <license>MIT</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>ffmpeg</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
